// <auto-generated />
using System;
using GerEsportes_BackEnd;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GerEsportes_BackEnd.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GerEsportes_BackEnd.Dominios.Agendas.Agenda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Categoria")
                        .HasColumnType("integer")
                        .HasColumnName("categoria");

                    b.Property<int>("CodigoLocal")
                        .HasColumnType("integer")
                        .HasColumnName("codigolocal");

                    b.Property<int>("CodigoUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("codigousuario");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datafim");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datainicio");

                    b.Property<DateTime>("DataSalvamento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datasalvamento");

                    b.Property<int>("Modalidade")
                        .HasColumnType("integer")
                        .HasColumnName("modalidade");

                    b.Property<string>("Obs")
                        .HasColumnType("text")
                        .HasColumnName("observacao");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipoevento");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("titulo");

                    b.HasKey("Id");

                    b.HasIndex("CodigoLocal");

                    b.HasIndex("CodigoUsuario");

                    b.ToTable("geragenda", (string)null);
                });

            modelBuilder.Entity("GerEsportes_BackEnd.Dominios.Emails.Email", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CodeRecover")
                        .HasColumnType("integer")
                        .HasColumnName("code_recover");

                    b.Property<string>("EmailFrom")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email_from");

                    b.Property<string>("EmailTo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email_to");

                    b.Property<int>("EnumStatusEmail")
                        .HasColumnType("integer")
                        .HasColumnName("status_email");

                    b.Property<string>("OwnerRef")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("owner_ref");

                    b.Property<DateTime>("SendDateEmail")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("send_date_email");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.HasKey("Id");

                    b.ToTable("geremail", (string)null);
                });

            modelBuilder.Entity("GerEsportes_BackEnd.Dominios.Locais.Local", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cep");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cidade");

                    b.Property<string>("Complemento")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("complemento");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("numero");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rua");

                    b.HasKey("Id");

                    b.ToTable("gerlocal", (string)null);
                });

            modelBuilder.Entity("GerEsportes_BackEnd.Dominios.Pings.PingEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Reponse")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("response");

                    b.HasKey("Id");

                    b.ToTable("Ping");
                });

            modelBuilder.Entity("GerEsportes_BackEnd.Dominios.Tokens.TokenAutenticationGer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("gertoken", (string)null);
                });

            modelBuilder.Entity("GerEsportes_BackEnd.Dominios.Usuarios.Documentos.DocumentoUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CodigoUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.Property<string>("Extensao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("extensao");

                    b.Property<string>("GuidDocumento")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("guiddocumento");

                    b.Property<bool>("ImagemPerfil")
                        .HasColumnType("boolean")
                        .HasColumnName("imagemperfil");

                    b.Property<string>("NomeDocumento")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nomedocumento");

                    b.HasKey("Id");

                    b.HasIndex("CodigoUsuario");

                    b.ToTable("gerdocumentousuario", (string)null);
                });

            modelBuilder.Entity("GerEsportes_BackEnd.Dominios.Usuarios.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cargo");

                    b.Property<int>("Categoria")
                        .HasColumnType("integer")
                        .HasColumnName("categoria");

                    b.Property<string>("CpfRg")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cpfrg");

                    b.Property<string>("Cref")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cref");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datanascimento");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Federacao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("federacao");

                    b.Property<int>("Genero")
                        .HasColumnType("integer")
                        .HasColumnName("genero");

                    b.Property<int>("Modalidade")
                        .HasColumnType("integer")
                        .HasColumnName("modalidade");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("Senha")
                        .HasColumnType("text")
                        .HasColumnName("senha");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("telefone");

                    b.Property<int>("Time")
                        .HasColumnType("integer")
                        .HasColumnName("timegenero");

                    b.Property<int>("TipoUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("tipousuario");

                    b.HasKey("Id");

                    b.ToTable("gerusuario", (string)null);
                });

            modelBuilder.Entity("GerEsportes_BackEnd.Dominios.Agendas.Agenda", b =>
                {
                    b.HasOne("GerEsportes_BackEnd.Dominios.Locais.Local", "Local")
                        .WithMany()
                        .HasForeignKey("CodigoLocal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GerEsportes_BackEnd.Dominios.Usuarios.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("CodigoUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Local");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GerEsportes_BackEnd.Dominios.Usuarios.Documentos.DocumentoUsuario", b =>
                {
                    b.HasOne("GerEsportes_BackEnd.Dominios.Usuarios.Usuario", "Usuario")
                        .WithMany("DocumentoUsuario")
                        .HasForeignKey("CodigoUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GerEsportes_BackEnd.Dominios.Usuarios.Usuario", b =>
                {
                    b.Navigation("DocumentoUsuario");
                });
#pragma warning restore 612, 618
        }
    }
}
